// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CenterContainer: typeof import('./src/components/center-container.vue')['default']
    CmpItem: typeof import('./src/components/cmp/cmp-item.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderContainer: typeof import('./src/components/header-container.vue')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiFilmstripBoxMultiple: typeof import('~icons/mdi/filmstrip-box-multiple')['default']
    LeftContainer: typeof import('./src/components/left-container.vue')['default']
    LibContainer: typeof import('./src/components/cmp/lib-container.vue')['default']
    RightContainer: typeof import('./src/components/right-container.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
